# Generated by Django 5.2.15 on 2026-06-25 17:25

import django.core.validators
import django.db.models.deletion
import dossiers.models
import dossiers.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dossier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("ACHAT", "Achat"), ("LOCATION", "Location")],
                        max_length=10,
                        verbose_name="type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("depose", "Déposé"),
                            ("EN_COURS", "En cours"),
                            ("valide", "Validé"),
                            ("REFUSE", "Refusé"),
                        ],
                        default="depose",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "motif_refus",
                    models.TextField(blank=True, verbose_name="motif de refus"),
                ),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="crée le"),
                ),
                (
                    "maj_le",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dossiers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-cree_le",),
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        upload_to=dossiers.models.chemin_piece,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=("pdf", "jpg", "jpeg", "png")
                            ),
                            dossiers.validators.validate_file_size,
                        ],
                        verbose_name="fichier",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="crée le"),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="dossiers.dossier",
                    ),
                ),
            ],
            options={
                "ordering": ("-cree_le",),
            },
        ),
    ]
