# Generated by Django 5.2.15 on 2026-06-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dossiers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dossier",
            name="status",
        ),
        migrations.AddField(
            model_name="dossier",
            name="statut",
            field=models.CharField(
                choices=[
                    ("depose", "Déposé"),
                    ("en_cours", "En cours"),
                    ("valide", "Validé"),
                    ("refuse", "Refusé"),
                ],
                default="depose",
                max_length=10,
                verbose_name="statut",
            ),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="type",
            field=models.CharField(
                choices=[("achat", "Achat"), ("location", "Location")],
                max_length=10,
                verbose_name="type",
            ),
        ),
    ]
