# Generated by Django 5.2.15 on 2026-06-25 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("assurance", "Assurance tous risques"),
                            ("assistance", "Assistance dépannage"),
                            ("sav", "Entretien et SAV"),
                            ("controle_technique", "Contrôle technique"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("libelle", models.CharField(max_length=80)),
                ("prix_mensuel", models.DecimalField(decimal_places=2, max_digits=8)),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("libelle",),
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duree_mois", models.PositiveIntegerField(default=36)),
                ("loyer_base", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_mensuel", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_engagement",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("brouillon", "Brouillon"), ("souscrit", "Souscrit")],
                        default="souscrit",
                        max_length=10,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contrats",
                        to="catalog.vehicle",
                    ),
                ),
                (
                    "options",
                    models.ManyToManyField(
                        blank=True, related_name="contrats", to="subscriptions.option"
                    ),
                ),
            ],
            options={
                "ordering": ("-cree_le",),
            },
        ),
    ]
